// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp5afKtlSdptQ8pjYPPuM0mjKtEuyF0jE',
    appId: '1:712155448709:web:c4028216e07ee063a4f0ec',
    messagingSenderId: '712155448709',
    projectId: 'may-two',
    authDomain: 'may-two.firebaseapp.com',
    storageBucket: 'may-two.appspot.com',
    measurementId: 'G-RWG49K7BJK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt_W3QS6euSCauDKGfOu8vgNtdpmSDMvs',
    appId: '1:712155448709:android:e2fee50cfab5d297a4f0ec',
    messagingSenderId: '712155448709',
    projectId: 'may-two',
    storageBucket: 'may-two.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBadBCfcR7xeWVE3GwUj_Y1ftkJaisRWbc',
    appId: '1:712155448709:ios:45ea873ac7573091a4f0ec',
    messagingSenderId: '712155448709',
    projectId: 'may-two',
    storageBucket: 'may-two.appspot.com',
    iosBundleId: 'com.example.mayTwo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBadBCfcR7xeWVE3GwUj_Y1ftkJaisRWbc',
    appId: '1:712155448709:ios:45ea873ac7573091a4f0ec',
    messagingSenderId: '712155448709',
    projectId: 'may-two',
    storageBucket: 'may-two.appspot.com',
    iosBundleId: 'com.example.mayTwo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBp5afKtlSdptQ8pjYPPuM0mjKtEuyF0jE',
    appId: '1:712155448709:web:702a2917e9022659a4f0ec',
    messagingSenderId: '712155448709',
    projectId: 'may-two',
    authDomain: 'may-two.firebaseapp.com',
    storageBucket: 'may-two.appspot.com',
    measurementId: 'G-G3SLYWTQTB',
  );
}
